### ISSUE TITLE
Make Group a value object

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_support#1]
If I create two Group instances with the same id, I should end up with the same object (or nearly).

To do this we need to implement 4 methods on Group:

```
#<=>(other)
#eql?(other)
#==(other)
#hash
```

See OSC::Machete::Status for an example.

**Comment by nickjer** [comment]
Yeah, I was debating that as well. Just wasn't sure if I'd use the id or the name.

**Comment by nickjer** [comment]
Since I made a group object have `#to_s`, and most often we will want to sort alphabetically, decided to go with `name` and not `id`.

**Comment by nickjer** [comment]
Fixed in 3219a589124ba2a3bda595c22d33e51e1ff68768

**Comment by ericfranz** [comment]
Won't using name and not id be significantly slower?

**Comment by ericfranz** [comment]
That said we aren't dealing with large arrays ha ha

**Comment by ericfranz** [comment]
Well, in the future, on each request we will be checking the Process group list against the User group list to verify whether they are the same or not.

**Comment by ericfranz** [comment]
In that case, maybe the spaceship operator could use `name` for comparison but the other operators (hash, eql,==) use `id`.

**Comment by nickjer** [comment]
I could switch out equality/hash for id.

**Comment by ericfranz** [comment]
That might be best, assuming that Array#==(other_array) does not make use of comparison operators.
